#!/bin/sh
# Prepend the Jira issue number to a commit message
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
# SHA1=$3

JIRA_ISSUE=$(git branch | grep -E "^\*" | grep -Eo "[A-Z]+-[0-9]{1,7}")
# If not a merge AND the branch has a jira issue AND the commit does not include it
if [ "$COMMIT_SOURCE" != "merge" ] && [ -n "$JIRA_ISSUE" ] && ! grep -E "$JIRA_ISSUE" "$COMMIT_MSG_FILE"; then
    COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
    echo "[$JIRA_ISSUE] $COMMIT_MSG" > "$1"
fi
