#!/bin/sh
# Prepend the Jira issue number to a commit message
JIRA_ISSUE="$(git branch | grep -E "^\*" | grep -Eo "[A-Z]+-[0-9]{1,7}")"
INCOMING_COMMIT_MESSAGE="$1"
FIRST_LINE_ALREADY_HAS_JIRA_ISSUE=`head -1 $1 | grep -E "$JIRA_ISSUE"`
if [ "$JIRA_ISSUE" -a ! "$FIRST_LINE_ALREADY_HAS_JIRA_ISSUE" -a "$2" != "merge" ]; then
  echo "[$JIRA_ISSUE] \c" > $1
  echo "$INCOMING_COMMIT_MESSAGE" >> $1
fi
